INSERT INTO candidato (nome, cpf, linkedin, email, telefone, curriculo, endereco) VALUES ('Raul Seixas', '08197701911', 'linkedin/mayara', 'raul@gmail.com', '991516340', 'resume', 'Rua blabs');
INSERT INTO candidato (nome, cpf, linkedin, email, telefone, curriculo, endereco) VALUES ('Renato Russo', '08197701921', 'linkedin/test', 'rr@gmail.com', '991514350', 'resume', 'Rua blabs');
INSERT INTO candidato (nome, cpf, linkedin, email, telefone, curriculo, endereco) VALUES ('Rita Lee', '08197701912', 'linkedin/ro', 'ritah@gmail.com', '991515540', 'resume', 'Rua blabs');
INSERT INTO candidato (nome, cpf, linkedin, email, telefone, curriculo, endereco) VALUES ('Elis Regina', '08197721911', 'linkedin/don', 'regininha@gmail.com', '9966555340', 'resume', 'Rua blabs');
INSERT INTO plano (nome, prioridade) VALUES ('FREE', 0);
INSERT INTO plano (nome, prioridade) VALUES ('PREMIUM', 1);
INSERT INTO plano (nome, prioridade) VALUES ('SUPER_PREMIUM', 2);
INSERT INTO empresa (nome_fantasia, razao_social, cnpj, linkedin, email, telefone, endereco, id_plano) VALUES ('Don Pet1', 'Don Company e cia1', '78297125000112', 'linkedin/don', 'don@gmail.com', '991514340', 'Rua blabs', 1);
INSERT INTO empresa (nome_fantasia, razao_social, cnpj, linkedin, email, telefone, endereco, id_plano) VALUES ('Don Pet2', 'Don Company e cia2', '00168416000113', 'linkedin/don', 'don@gmail.com', '991514340', 'Rua blabs', 2);
INSERT INTO empresa (nome_fantasia, razao_social, cnpj, linkedin, email, telefone, endereco, id_plano) VALUES ('Don Pet3', 'Don Company e cia3', '10145243000171', 'linkedin/don', 'don@gmail.com', '991514340', 'Rua blabs', 3);
INSERT INTO competencia (nome) VALUES ('JAVA');
INSERT INTO competencia (nome) VALUES ('HTML');
INSERT INTO competencia (nome) VALUES ('CSS');
INSERT INTO competencia (nome) VALUES ('JAVASCRIPT');
INSERT INTO candidato_competencia (id_candidato, id_competencia) VALUES (1, 1);
INSERT INTO candidato_competencia (id_candidato, id_competencia) VALUES (1, 2);
INSERT INTO candidato_competencia (id_candidato, id_competencia) VALUES (2, 4);
INSERT INTO candidato_competencia (id_candidato, id_competencia) VALUES (3, 1);
INSERT INTO candidato_competencia (id_candidato, id_competencia) VALUES (4, 1);
INSERT INTO candidato_competencia (id_candidato, id_competencia) VALUES (4, 2);
INSERT INTO candidato_competencia (id_candidato, id_competencia) VALUES (2, 3);
INSERT INTO candidato_competencia (id_candidato, id_competencia) VALUES (4, 4);
INSERT INTO candidato_competencia (id_candidato, id_competencia) VALUES (3, 4);
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (1, 'Vaga 1', 'Descrição da vaga 1', 'OPEN', 5000.00, 'MID');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (1, 'Vaga 2', 'Descrição da vaga 2', 'OPEN', 8500.50, 'SENIOR');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (2, 'Vaga 3', 'Descrição da vaga 3', 'CLOSED', 5000.00, 'MID');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (3, 'Vaga 4', 'Descrição da vaga 4', 'OPEN', 11500.50, 'SENIOR');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (1, 'Vaga 5', 'Descrição da vaga 5', 'OPEN', 8500.50, 'SENIOR');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (1, 'Vaga 6', 'Descrição da vaga 6', 'OPEN', 10300.13, 'SENIOR');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (2, 'Vaga 7', 'Descrição da vaga 7', 'OPEN', 11600.14, 'SENIOR');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (3, 'Vaga 8', 'Descrição da vaga 8', 'CLOSED', 5000.00, 'MID');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (1, 'Vaga 9', 'Descrição da vaga 9', 'OPEN', 8500.50, 'SENIOR');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (1, 'Vaga 10', 'Descrição da vaga 10', 'OPEN', 2500.13, 'ENTRY');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (2, 'Vaga 11', 'Descrição da vaga 11', 'OPEN', 11500.50, 'SENIOR');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (3, 'Vaga 12', 'Descrição da vaga 12', 'OPEN', 8500.50, 'SENIOR');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (1, 'Vaga 13', 'Descrição da vaga 13', 'CLOSED', 5000.00, 'MID');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (1, 'Vaga 14', 'Descrição da vaga 14', 'OPEN', 4600.13, 'ENTRY');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (2, 'Vaga 15', 'Descrição da vaga 15', 'OPEN', 8500.50, 'SENIOR');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (3, 'Vaga 16', 'Descrição da vaga 16', 'OPEN', 6900.15, 'SENIOR');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (1, 'Vaga 17', 'Descrição da vaga 17', 'OPEN', 5000.00, 'MID');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (1, 'Vaga 18', 'Descrição da vaga 18', 'CLOSED', 11500.50, 'SENIOR');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (2, 'Vaga 19', 'Descrição da vaga 19', 'OPEN', 11500.50, 'SENIOR');
INSERT INTO vaga (id_empresa, nome, descricao, status, remuneracao, senioridade) VALUES (3, 'Vaga 20', 'Descrição da vaga 20', 'OPEN', 5000.00, 'MID');
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (1, 1);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (1, 2);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (1, 3);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (2, 4);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (3, 3);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (4, 2);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (5, 4);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (6, 2);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (7, 3);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (8, 2);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (9, 1);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (10, 2);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (11, 1);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (12, 3);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (13, 2);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (14, 4);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (15, 2);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (16, 1);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (16, 2);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (16, 4);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (17, 4);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (18, 4);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (19, 3);
INSERT INTO vaga_competencia (id_vaga, id_competencia) VALUES (20, 2);
INSERT INTO candidato_vaga (id_candidato, id_vaga) VALUES (1, 1);
INSERT INTO candidato_vaga (id_candidato, id_vaga) VALUES (1, 2);
INSERT INTO candidato_vaga (id_candidato, id_vaga) VALUES (2, 1);

